name: bank
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  dartz: ^0.10.1
  firebase_core: ^2.28.0
  firebase_database: ^10.5.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  freezed: ^2.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  provider: ^6.1.2

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
