// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhRNmDMIhL7GdCnZ5VhvZvWd-jT8zRyS4',
    appId: '1:988471013249:web:de7d7faee76e1f2b010280',
    messagingSenderId: '988471013249',
    projectId: 'bank-1260a',
    authDomain: 'bank-1260a.firebaseapp.com',
    databaseURL: 'https://bank-1260a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bank-1260a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRu9zE9_noSIhmuC6orZGjvBehabkIrg0',
    appId: '1:988471013249:android:0f7ec300682e4086010280',
    messagingSenderId: '988471013249',
    projectId: 'bank-1260a',
    databaseURL: 'https://bank-1260a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bank-1260a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh0e1IZnkPCKsEF4J0jykCZrTtcHe-4UY',
    appId: '1:988471013249:ios:131de3ffe39c9198010280',
    messagingSenderId: '988471013249',
    projectId: 'bank-1260a',
    databaseURL: 'https://bank-1260a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bank-1260a.appspot.com',
    iosBundleId: 'com.example.bank',
  );
}
